// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PopcornMovie/ent/room"
	"PopcornMovie/ent/theater"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TheaterCreate is the builder for creating a Theater entity.
type TheaterCreate struct {
	config
	mutation *TheaterMutation
	hooks    []Hook
}

// SetAddress sets the "address" field.
func (tc *TheaterCreate) SetAddress(s string) *TheaterCreate {
	tc.mutation.SetAddress(s)
	return tc
}

// SetName sets the "name" field.
func (tc *TheaterCreate) SetName(s string) *TheaterCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetPhoneNumber sets the "phone_number" field.
func (tc *TheaterCreate) SetPhoneNumber(s string) *TheaterCreate {
	tc.mutation.SetPhoneNumber(s)
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TheaterCreate) SetCreatedAt(t time.Time) *TheaterCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TheaterCreate) SetNillableCreatedAt(t *time.Time) *TheaterCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TheaterCreate) SetUpdatedAt(t time.Time) *TheaterCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TheaterCreate) SetNillableUpdatedAt(t *time.Time) *TheaterCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetID sets the "id" field.
func (tc *TheaterCreate) SetID(u uuid.UUID) *TheaterCreate {
	tc.mutation.SetID(u)
	return tc
}

// AddRoomIDs adds the "rooms" edge to the Room entity by IDs.
func (tc *TheaterCreate) AddRoomIDs(ids ...uuid.UUID) *TheaterCreate {
	tc.mutation.AddRoomIDs(ids...)
	return tc
}

// AddRooms adds the "rooms" edges to the Room entity.
func (tc *TheaterCreate) AddRooms(r ...*Room) *TheaterCreate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tc.AddRoomIDs(ids...)
}

// Mutation returns the TheaterMutation object of the builder.
func (tc *TheaterCreate) Mutation() *TheaterMutation {
	return tc.mutation
}

// Save creates the Theater in the database.
func (tc *TheaterCreate) Save(ctx context.Context) (*Theater, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TheaterCreate) SaveX(ctx context.Context) *Theater {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TheaterCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TheaterCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TheaterCreate) defaults() {
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := theater.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := theater.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TheaterCreate) check() error {
	if _, ok := tc.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Theater.address"`)}
	}
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Theater.name"`)}
	}
	if _, ok := tc.mutation.PhoneNumber(); !ok {
		return &ValidationError{Name: "phone_number", err: errors.New(`ent: missing required field "Theater.phone_number"`)}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Theater.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Theater.updated_at"`)}
	}
	return nil
}

func (tc *TheaterCreate) sqlSave(ctx context.Context) (*Theater, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TheaterCreate) createSpec() (*Theater, *sqlgraph.CreateSpec) {
	var (
		_node = &Theater{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(theater.Table, sqlgraph.NewFieldSpec(theater.FieldID, field.TypeUUID))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tc.mutation.Address(); ok {
		_spec.SetField(theater.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(theater.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.PhoneNumber(); ok {
		_spec.SetField(theater.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(theater.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(theater.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := tc.mutation.RoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theater.RoomsTable,
			Columns: []string{theater.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TheaterCreateBulk is the builder for creating many Theater entities in bulk.
type TheaterCreateBulk struct {
	config
	err      error
	builders []*TheaterCreate
}

// Save creates the Theater entities in the database.
func (tcb *TheaterCreateBulk) Save(ctx context.Context) ([]*Theater, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Theater, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TheaterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TheaterCreateBulk) SaveX(ctx context.Context) []*Theater {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TheaterCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TheaterCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
