package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"PopcornMovie/ent"
	graphql1 "PopcornMovie/graphql"
	"context"
	"fmt"
)

// ID is the resolver for the id field.
func (r *commentResolver) ID(ctx context.Context, obj *ent.Comment) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Movie is the resolver for the movie field.
func (r *commentResolver) Movie(ctx context.Context, obj *ent.Comment) (*ent.Movie, error) {
	panic(fmt.Errorf("not implemented: Movie - movie"))
}

// User is the resolver for the user field.
func (r *commentResolver) User(ctx context.Context, obj *ent.Comment) (*ent.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Comment returns graphql1.CommentResolver implementation.
func (r *Resolver) Comment() graphql1.CommentResolver { return &commentResolver{r} }

type commentResolver struct{ *Resolver }
