package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"PopcornMovie/ent"
	graphql1 "PopcornMovie/graphql"
	"context"
)

// ID is the resolver for the id field.
func (r *roomResolver) ID(ctx context.Context, obj *ent.Room) (string, error) {
	return obj.ID.String(), nil
}

// Theater is the resolver for the theater field.
func (r *roomResolver) Theater(ctx context.Context, obj *ent.Room) (*ent.Theater, error) {
	return obj.Edges.Theater, nil
}

// ShowTime is the resolver for the showTime field.
func (r *roomResolver) ShowTime(ctx context.Context, obj *ent.Room) ([]*ent.ShowTime, error) {
	return obj.Edges.ShowTimes, nil
}

// Seat is the resolver for the seat field.
func (r *roomResolver) Seat(ctx context.Context, obj *ent.Room) ([]*ent.Seat, error) {
	return obj.Edges.Seats, nil
}

// Room returns graphql1.RoomResolver implementation.
func (r *Resolver) Room() graphql1.RoomResolver { return &roomResolver{r} }

type roomResolver struct{ *Resolver }
