version: "3"

networks:
  backend-api:
    driver: bridge

volumes:
  postgres_data:
    driver: local

services:
  db:
    image: postgres:13.8
    restart: always
    healthcheck:
      test: ["CMD-SHELL","pg_isready"]
      interval: 5s
      retries: 3
      timeout: 5s
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./scripts/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"
    networks:
      - backend-api


  atlas:
    image: arigaio/atlas:latest
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    volumes:
      - "./migrations/:/migrations"
    links:
      - "db"
    networks:
      - backend-api